### ISSUE TITLE
[Question] Compatability

### ISSUE THREAD

**Issue by egeis** [Deadrik/TFC2#3]
I noticed that a second version of this mod is being written, I am a bit of a fan and have followed some of this mods development and the previous versions.  I am disappointed in the incompatibility caused however with the architecture of TFC1.  Tools don't use base minecraft classes so other mods cannot interact with the first version without fundamental changes and vice versa with other block materials that use minecraft classes. TFC Logs are not actually Logs... An axe has to be a element in an array deep in TFC to be an "axe" if I recall dealing with Flax Bears Steam axe...

This summer I spend a month trying to keep Flax Beards steam power compatible with TFC1, I gave up as it was too time consuming to re-implement changes every time a version increased.  

I would love to participate a little in the development, hunting for work and need to keep my java skillz up, but I'd not like to see a repeat of some of the same compatibility issues with TFC 1.  Will this be a total conversion like the first version where you will be writing your own architecture and ignore base classes or will this new version be developed differently than the past?

**Comment by Kittychanley** [comment]
I would just like to point out that almost every single compatibility issue with TFC1 only exists in the current version because literally nobody has told us that it exists. You can't expect us to try our mod with every single other mod out there, and you can't expect us to read minds. The issue with axes was only brought to my attention a week ago. Before then, I had literally no idea it was even a problem. And what happened when it was brought to my attention? Within a few days a fix was made to make compatibility infinitely easier with the help of the ore dictionary. We can't fix something if we don't know it's broken. If you want to help, then you need to tell us what you think is broken and why. Small compatibility things like with the axe I am more than happy to still fix for TFC1.

**Comment by egeis** [comment]
I'll be happy to make issues for the bugs ive found for TFC1, on the tracker for that repository if you like.

**Comment by Kittychanley** [comment]
No actually. You'll see there's an issue on that tracker that explicitly states bugs for the release should be reported on the forums.

**Comment by egeis** [comment]
Ok, ill talk with one of the mod authors I've worked with first then report over there the bugs and issues from TFC1.  Are you looking for any developers help? I'd love to be able to report and have a fix ready when possible or pitch in with some development.

**Comment by Kittychanley** [comment]
The readme of that repo was recently updated, there's a section in it about contributing.

**Comment by egeis** [comment]
Thank you, i found the section under the other repo.
