### ISSUE TITLE
[API] Breaking changes

### ISSUE THREAD

**Issue by maxnordlund** [Deadrik/TFC2#4]
Hi, first let me say TFC is an awesome mod that is really inspiring and shows that modding can be done with high quality.

But as you are making a new version, and has already said it will come with breaking changes, this is perhaps the time to also do the same for the API. I mostly would like to see the hard dependencies of the API on the rest of the code broken out, but that might be to much trouble.

Anyways I figured I create an issue to discuss and track potential breaking changes (to be) made to the API.

**Comment by Deadrik** [comment]
Although I have some things split off into the api, from what I've seen of other modders making addons for TFC1, they just build their mod with the full TFC codebase in their development environment, so it almost seems useless. That said, although tfc2 is very heavily under development and nothing is really final, if you want to PR in some api specific changes, I'll at least take a look. I'll also admit that I've never written a proper API before in my life and am more than willing to look at better practices for such if you have any examples or pointers :)

**Comment by egeis** [comment]
What should your API Include: Interfaces and Abstract classes to create any item, tool, block, or expand on any process you have in your mod.  Using more base Minecraft classes for tools, blocks, and items you can probably get away with just using Interfaces and events, and on a plus side improve compatibility with EVERY mod out there.

One of the reasons we have to use your mods codebase in every project (TFC1) is because the lack of abstraction.  If I want to add a new tool I either need an interface to the API, or I need to interface to the API and extend it off a non-standard TFC tool class, and don’t forget my favorite, I need to interface to the API and extend it off a non-standard TFC tool class AND register it in a pre-set array of “accepted” tools to be used on the Block.

API development starts when you start writing code, it’s not always a good idea to add it after the fact.  This is double the case for your mod since your code base insists on changing and overriding Minecraft classes that other modders use as there base for development.
Don’t forget to include documentation on the use of your API abstract the classes that modders need to addon.  Good luck on the TFC2 re-write.

Article on Interfaces and Abstract Classes:
http://www.developer.com/lang/article.php/10924_3642656_2/Designing-with-Interfaces-amp-Abstract-Classes.html

Best Practices Article:
http://blog.jooq.org/2013/08/20/10-subtle-best-practices-when-coding-java/

**Comment by dexman545** [comment]
I would also like to add that that creating custom blocks that do not register themselves as proper types that exist in MC already breaks compatibility with other mods. It is possible to increase the hardness of any block in game already, or at least it was during 1.6.4/1.7.10, as evidenced with this mod: https://github.com/Parker8283/IguanaTweaks

**Comment by Deadrik** [comment]
The core minecraft aspects have barely been worked on at this point. Most of the code is on the worldgen side. Question then for those that have made addons, what is the point of spending the time to write the api? What do you gain from having the api vs just compiling against the full codebase? If TFC were closed source then obviously I'd see the purpose. I'm just curious what you're gaining here?

**Comment by Xechon** [comment]
I've never finished an addon, but I would like to mention that structuring code to support an api makes it much easier to hook into functionality and even change it. If you keep using registries and events regularly it shouldn't matter if there is an actual api. Just think composition over inheritance if you want to promote addons without a ton of PRs for more hooks.

**Comment by egeis** [comment]
I'd personally like to see the use of Interfaces for new tools rather than the inheriting base TFC classes.  Rather than registering each tool in a list, how about checking if they are an (example: InstanceOf TerraTool.)  This approach you can eventually create several methods to bridge other mods, using one of two methods: Using the Interface in your mod or alternatively using some sort of configuration.

**Comment by FailMelon** [comment]
This is a bit late but i thought i'd pitch in to answer why you should use an api vs compiling against the full codebase.

1: Codebase changes, an api allows things to be more set in stone freeing up codebase drastic changes with making compatibility more easier for modders. We all know how this has gone down in the past with a lack thereof with minecraft not having a solid api to work off of.

2: Usercode Error and bad implementation, an api causes less errors and makes things more standardized allowing implementations to all go through one system. Rather then custom made systems that may end up causing incompatibility.

3: Readability, an api allows for easier readability about what code does and how things work. Not only is it easier for modders to go through interfaces rather then massive piles of code it is also easier for documenting parts of the code that need to be documented.

4: Hardcode, an api helps free up one of the most annoying issues for modders and that is hardcoded content. Classes that are fixed in such a way as the only means of modification is via the means of script injection/reflection and patching(Forge). This again leads to incompatibility between mods that try to access similar content or a central library that someone makes that everyone uses yet some wont.

These and a bunch of other reasons why making an api is good, obviously with the downside of making an api and that is time.
