### ISSUE TITLE
[Java Version]

### ISSUE THREAD

**Issue by raymondbh** [Deadrik/TFC2#8]
I have converted your deprecated rendering registry calls to the new method, but this leaves two options. Go for the new Java 8 implement or keep Java 6/7 support? I have the new Java 8 code ready for you to pull.

**Comment by raymondbh** [comment]
I've have a solution to the Java 6/7 method almost ready too, so you can just choose what you think is best... I can make a pull request on both of them when I get home from work.

**Comment by dries007** [comment]
I'd advice against java 8. The mac people has enough issues with 7 as it is.

**Comment by Deadrik** [comment]
I closed the PRs as I implemented this myself in a decent way so that we can keep java 7 working. That said, I compile on java 8 so I've no idea if I've broken other things elsewhere.

**Comment by dries007** [comment]
If you want to be sure, add this to the gradle.build file:

``` java
sourceCompatibility = 1.7
targetCompatibility = 1.7
```

Normally that should be in the root, but in this case, I think inside the `allprojects` block should work.
You could test it by just adding a java 8 construct somewhere and trying to `gradle build`. I think it should even catch java 8 methods calls, but I'm not sure about that.

**Comment by CHeuberger** [comment]
not sure how this works with Gradle, but in Eclipse (or plain java) setting compatibility to 7 will NOT avoid calling methods introduced in Java 8 - the compiler compiles against the libraries set in the build path - in Eclipse you must configure the project properties to use the correct JRE System Library. I assume it must be similar with Gradle...

**Comment by dries007** [comment]
I thought it might use the `since` annotation to throw errors. I'll science it when I get home.

**Comment by Angelo-Verona** [comment]
Go for Java 8, I have mac and I don't have any issues different then what
java 7 had(installation wise) and there is tons of videos and tutorials how
to install and conf Java8,  TFC also with java 8 will last longer as a
product and gives more breathing room fro you and mod devs. And will not
affect all other platforms, because one of them had kind of issues?Java 7
is no longer supported.Unless you desperately need to program in Java7 as
predefined target platform, go for Java 8.

On Wednesday, April 13, 2016, Dries007 notifications@github.com wrote:

> I thought it might use the since annotation to throw errors. I'll science
> it when I get home.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Deadrik/TFC2/issues/8#issuecomment-209414260

## 

ANGELO VERONASenior IT Consultant

_Grösslingová 23, 811 09 Bratislava_
- e: angelo.verona@ligapassage.sk
- m: +(421) 902 624 129

_Pravne informacie:_ Tento e-mail a vsetky pripojene subory su doverne a
mozu byt chranene zakonom. Pokial nie ste opravnenym prijemcom, potom
akakolvek forma zverejnovania, reprodukovania, kopirovania, distribucie
alebo sirenia je prisne zakazana. Ak ste obdrzali tento e-mail omylom,
oznamte to, prosim, okamzite na angelo.verona@ligapassage.sk a nasledne
zmazte tento e-mail. Angelo Verona nezodpoveda za bezchybny a uplny prenos
zasielanych informacii, ani za oneskorenie alebo prerusenie prenosu a ani
za skody sposobene pouzitim alebo doverou k tymto informaciam. Vsetky
e-mailove spravy adresovane, obdrzane alebo zaslane od Angelo Verona su
povazovane za cisto pracovne.
_Legal Disclaimer:_ This e-mail and any attached files are confidential and
may be legally privileged. If you are not the addressee, any disclosure,
reproduction, copying, distribution, or other dissemination or use of this
communication is strictly prohibited. If you have received this
transmission in error please notify angelo.verona@ligapassage.sk immediately
and then delete this e-mail. Angelo Verona does not accept liability for
the correct and complete transmission of the information, nor for any delay
or interruption of the transmission, nor for damages arising from the use
of or reliance on the information. All e-mail messages addressed to,
received or sent by Angelo Verona are deemed to be professional in nature.
